export const types = {
    START_FETCHING      : 'START_FETCHING',
    STOP_FETCHING       : 'STOP_FETCHING',
    EMIT_ERROR          : 'EMIT_ERROR',
    SEARCH_TASKS        : 'SEARCH_TASKS',
    ALL_COMPLETED_TASKS : 'ALL_COMPLETED_TASKS',
}
